name: build
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8', '3.9', 'pypy3']
        exclude:
          - os: windows-latest
            python: pypy3
          - os: macos-latest
            python: '3.9'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_NO_INTERACTION: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade poetry pip
      - run: poetry install --ascii
      - run: poetry run pytest
